server:
  port: ${PORT:8081}
  ip: localhost

spring:
  application:
    name: users-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:users}?useSSL=false
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:andreevich}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        format_sql: true
        default_schema: users_scheme
        cache:
          use_second_level_cache: true
          region:
            factory_class: jcache
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    default-schema: users_scheme
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Skillagram
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

log4j2:
  contextSelector: org.apache.logging.log4j.core.async.AsyncLoggerContextSelector

jwt:
  auth:
    converter:
      resource-id: users-api
      principal-attribute: preferred_username

