server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: andreevich
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.default_schema: users_scheme
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    schemas: users_scheme

server_ip: ${SERVER_IP:localhost}