package ru.borisov.users.exception.error;

public enum Code {

    BAD_REQUEST,
    CONFLICT,
    USER_NOT_FOUND,
    REQUEST_VALIDATION_ERROR,
    LOGIN_BUSY,
    BAD_CREDENTIALS,
    PHONE_NUMBER_BUSY,
    CONTRACT_APPLICATION_NOT_EXIST,
    INTERNAL_SERVER_ERROR,
    SERVICE_UNAVAILABLE
}
