#eval $(minikube docker-env) -- команда docker будет смотреть образы внутри minikube

apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-backend-deployment
  labels:
    app: users-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-backend # запускает 2 poda c меткой users-backend
  template:
    metadata:
      labels:
        app: users-backend
    spec:
      containers:
      - name: users-service
        image: ascjke/users-service
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://postgres:5432/users

      - name: users-postgres-db
        image: postgres:15-alpine
        ports:
        - containerPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: users-backend-service
spec:
  selector:
    app: users-backend # смотрит podы c меткой users-backend
  ports:
    - protocol: TCP
      port: 80 # порт сервиса внутри кластера
      targetPort: 8080 # внешний порт сервиса