#eval $(minikube docker-env) -- команда docker будет смотреть образы внутри minikube

apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-backend-deployment
  labels:
    app: users-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-backend # запускает 2 poda c меткой users-backend
  template:
    metadata:
      labels:
        app: users-backend
    spec:
      initContainers:
        - name: liquibase
          image: liquibase/liquibase:4.20.0
      containers:
      - name: users-service
        image: ascjke/users-service
        ports:
        - containerPort: 8080
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: host

          - name: DB_NAME  # Setting Database name from configMap
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: dbName

          - name: DB_USERNAME  # Setting Database username from Secret
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: username

          - name: DB_PASSWORD # Setting Database password from Secret
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: password

---
apiVersion: v1
kind: Service
metadata:
  name: users-backend-service
spec:
  selector:
    app: users-backend # смотрит podы c меткой users-backend
  ports:
    - protocol: TCP
      port: 8080 # порт сервиса внутри кластера
      targetPort: 8080 # внешний порт сервиса

# kubectl port-forward service/users-backend-service 8080:8080

