version: '3'

services:
  postgres:
    image: postgres:15-alpine
    container_name: users-postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users
    ports:
      - 5432:5432
    volumes:
      - ./users-service-data:/var/lib/postgresql/data
    command: postgres -c shared_buffers=32MB -c temp_buffers=8MB
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M
    restart: always

  users:
    build: ./
    container_name: users-service
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/users
      - TZ=Asia/Yakutsk
      - JAVA_TOOL_OPTIONS=-XX:+UseG1GC -Xmx960m -Xms128m
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - ./logs:/application/logs
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 128M



